### ISSUE TITLE
Multiple proxy chain Feature

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpProxyR66#29]
Hi,

At the moment, is possible to chain multiple R66 proxies in front of a R66 server? Could you confirm that?

Regards

Alex

**Comment by fredericBregier** [comment]
Hi,

Honnestly, this configuration was never tested.

If I understand well, what you want is something like:

Waarp R66 (client or server) => Proxy R66 1 => Proxy R66 2 => Waarp R66 Server

It should be possible, as long as you defined the correct path:

Let say you have:
- 2 servers A and B respectively using [IpA,PortA] and [IpB,PortB] oustide, 
- and 2 servers C and D respectively using [IpC,PortC] and [IpD,PortD] inside, 
- then 2 proxies X and Y with IpX/Ip'X and IpY/Ip'Y 
- where IpX is reachable from IpA and IpB, 
- Ip'X reachable from IpY, 
- and Ip'Y reachable from IpC and IpD

Which gives from "macro" network perspective:

- external "network" IpA, IpB, IpX
- internal "network" IpC, IpD, Ip'Y
- same "cross network" Ip'X, IpY

Then you will have to ensure the paths exist such that:

- when someone (A or B) wants to reach C, there is one unique path, such as: [IpX,portXC]/[Ip'X,port'XC]/[IpY,portYC]/[Ip'Y,port'YC]/[IpC,portC]

- Same for D, and reversely same for A and B.

Of course, portXC, port'XC, portYC, port'YC could be whatever, as long as the chan is unique and respected, meaning if you reach [IpX,portXC], in fact you reach [IpC,portC].

I don't know if I'm clear enough (not so easy with such configuration). I would suggest of course to have a clean rule of port assignement, such as there is no difficulties on your proxy configurations.

For instance:
- if C is on port 6660, and D on port 6661, then you can assign safely the same port on the proxies
- but if they do have the same port (6666 for instance), then you should try to have a rule such as C proxy port is 7066 and B proxy port is 7166 (or whatever other rules)

I would be interesting to know if it works ;-)

**Comment by alexbarta** [comment]
Yes, the configuration you excellently wrote corresponds to what I have in my mind.. I'm going to try this out in the next days and I'll report here my progress so also others can benefit.

Thanks

**Comment by alexbarta** [comment]
Hi,

Following your example, I would add some details to the discussion. 

I have three network layers (DMZ,a mid layer and intranet )  and clients A,B located on internet communicate through proxies with nodes C,D (intranet). 
So in my case, client A or B send/receive data connecting to a public IP without knowing which MFT architecture is behind. 

Here comes my doubt: 
I need multiple R66 servers to handle multiple segregated transfer flows (eg. Many to many relationship).  
If I choose to use same port for all chained proxies which means that all transfer flows are proxied by same proxy servers, can client A tell the final proxy to route a specific datafile to server D in place of server C and viceversa? Or do I need to create multiple proxy:port servers for each transfer flow to be handled?

One thing I was wondering about after reading the docs, is whether proxy server can be connected to a list of servers instead of single one.

To be more explicit I also attach a schema I did:
![image](https://cloud.githubusercontent.com/assets/9393789/12427425/81dc134a-bedf-11e5-9d9c-15b7cf49ed97.png)

Thanks for you time

**Comment by fredericBregier** [comment]
OK, it seems I was not so clear (not suprsing myself ;-)
The proxy chain is this way:
- serverlistenaddr/serverlistenport (and serverlistenssl for ssl) is the entry point of the proxy linked to one and unique
- serverremoteaddr/serverremoteport (and same serverremotessl) which is the target

Indeed, I wrongly write my explanation in my previous post (to quick to answear).
So I will try again, trying to correct myself, but then be long and probably repetitive... sorry.

Let say, same example:

- 2 servers A and B respectively using [IpA,PortA] and [IpB,PortB] oustide,
- 2 servers C and D respectively using [IpC,PortC] and [IpD,PortD] inside,
- 2 proxies X and Y with IpX/Ip'X and IpY/Ip'Y (', so the second IP being inside)

Let say for the simplicity that A, B, C and D all use different ports (portA != portB != portC != portD).
Then you have a chain for C as:
- on X IpX:portC (serverlisten part on Internet network) => Y IpY:portC (serverremote part on DMZ network)
- on Y IPY:portC (serverlisten part on DMZ network) => C IpC:portC (serverremote part on MID-LAYER network)

Note that network change occur through "host" configuration, meaning:
- on X, a network flow from IpX:portC (Internet) will be proxified to IpY:portC (DMZ) using the route as defined on the host X, so from an Ip'X on DMZ on host X
- same on Y from DMZ to MID-LAYER

So you don't have to specify the 2 ports on the same proxy server as I said before (no Ip'X:portC defined at all). The outgoing used port is dynamic.

Now using this configuration, whatever A or B could access to C through this chain, but C cannot access (at its initiative, so opening the socket) to A and B.

If the reverse is wanted (as assumed), then you have to do the same for A and B reversely:
Then you have a chain for A as:
- on Y IP'Y:portA (serverlisten part on MID-LAYER network) => X Ip'X:portA (serverremote part on DMZ network)
- on X Ip'X:portA (serverlisten part on DMZ network) => A IpA:portA (serverremote part on Internet network)

So for each server, whatever the position, you will have to build a chain from the farest proxy to him through 2 definitions:
- farest proxy listening port X cibling middle proxy port X
- middle proxy listening port X cibling target port X
(of course if port X is different for each server ; if not, you have to make you own rule for port numbering as said previously).

So in you case:
- Proxy in front of DMZ: 2 rules for listening for flows to servers C and D through Proxy DMZ
- Proxy in DMZ: 2 rules for listening for flows to servers C and D from Proxy in front of DMZ
- Proxy in front of DMZ: 2 rules for listening for flows to servers A and B from Proxy DMZ
- Proxy in DMZ: 2 rules for listening for flows to servers A and B through Proxy in front of DMZ

You have to create one chain for each targetting servers, but not for source ones.
So if you have let say 1000 clients outside, but still 2 servers inside, then only 2 chains must be defined to reach the 2 servers inside, defined on external IP of both waarp proxy.
But if you want to be able to reach the 1000 clients outside (being servers then), then you need 1000 definitions too (in the reverse way) defined on internal IP of both waarp proxy.

It's all depend on your needs. Generally, such configuration is more to be able to reach internal Waarp servers than to go out, since outside clients can have pull or push requests, the initiative of the request being on client side. But if you need your 2 internal servers to be able to initiate a transfer (whatever the way push/pull), then you need indeed to define one entry point per remote client.

And yes, one proxy could handle as much as the number of ports are available simultaneously on the host, so, depending on various consideration, probably max around 60K external client (Inside->outside) + 60K internal servers (outside->inside) cumutatively (since the host is supposed to have 2 IPs, one for inside, one for outside).

**Comment by alexbarta** [comment]
Ok thanks for such detailed response.

As I feared, since I have many intranet servers, I should open as many ports as servers on external IP and currently I cannot.

So I was thinking about a kind of "workaround architecture" where instead of having a proxy port for each server, I configure a "special" R66 server that acts as dispatcher towards others R66 servers by taking advantage of posttask/pretask rule configuration "TRANSFER".

So in this case, let's reason on the transfer flow from internet client A to intranet server C using a dispatcher. 

Client A pushes datafile to outer Proxy X listening on dispatcher port (let's say PortDisp), then proxy X forwards traffic to inner proxy Y listening to PortDisp as well, and targeting dispatcher server on its port. 
So client A targets Dispatcher server in his SEND RULE actually ignoring where server C is (but dispatcher knows that in his Authent xml). In the end dispatcher sends data file to server C by executing TRANSFER posttask that targets C, as specified in SEND RULE used by  client A. (In a RECV rule may I consider TRANSFER as pretask as well?)

Fortunately enough, transfer flows from intranet servers to exterior clients are just a few, so it's not a problem deploying multiple chains in that case. My main constraint is limiting incoming connections.


Do you consider this a viable approach?

**Comment by fredericBregier** [comment]
Yes it is correct. That's one way to minimize the number of "visible" (through proxy) internal servers.
Indeed that's the way we integrate other protocols (let say I have on one server a protocole A and Waarp, then everything goes like you described, and no other server except this particular server knows about the others). It is what we called "a gateway configuration".

Here you mix proxy and "gateway" usage, that's fine.

To answer the small question on RECV:
- SEND : post action to forward
- RECV : pre action to "inward" the RECV first before doing the real RECV ; take care of timeout however since the first RECV (pre-action) might be long. However Waarp should be ok with that (since it maintains the connection).

The main issue will be the follow of the transfers since you have one server in the middle (gateway) that "breaks" the protocol (even if there the protocol is the same).
Note however that the Waarp Manager should be able to track this too and giving you therefore a complete vision of your transfers from end-to-end. (Note for Waarp Manager, please do ask the support directly, not through github since it is not Open source).

**Comment by fredericBregier** [comment]
Any new issue on that point?

**Comment by alexbarta** [comment]
Hey!

I'm glad to inform you that I was able to get the two proxies working together! I'll let you know, If I encounter some issue with this configuration.. I think you can close this one..

**Comment by fredericBregier** [comment]
Thanks!!
